Tutorial viewport
monoDriveIO/documentation pull request #205
Opened 2020-09-08 19:21 UTC by citlaligm

The purpose of this PR is to create a small tutorial on how to configure a multi viewport as well as update the viewport configuration to include new tags. 
Closes #178

2020-10-05 13:32 UTC, devinaconley requested changes
Looks good! Just need to make a few updates for the newer format. 

Check out this example here:
https://github.com/monoDriveIO/monodrive-client/blob/development/examples/cpp/dev/multi_viewport.cpp

2020-10-05 13:32 UTC, devinaconley commented on docs/LV_client/tutorials/Multi viewport.md
> +Note: A value of zero on the `"listen_port"` is reserve for the main viewport.
Good note. Now the entire `ViewportCamera` sensor config is a special case to set the game viewport

2020-10-05 13:32 UTC, devinaconley commented on docs/LV_client/tutorials/Multi viewport.md
> +Starting from release **1.12** the user can now configure secondary viewports. Modify the `"listen_port"` on the sensor configuration with any non-zero value to create additional viewports. User can
*on any standard, fisheye, or 360 camera

2020-10-05 13:32 UTC, devinaconley commented on docs/LV_client/tutorials/Multi viewport.md
> +Starting from release **1.12** the user can now configure secondary viewports. Modify the `"listen_port"` on the sensor configuration with any non-zero value to create additional viewports. User can
now we enable it with `viewport.enable_viewport`

2020-10-05 13:32 UTC, devinaconley commented on docs/LV_client/tutorials/Multi viewport.md
> +Starting from release **1.12** the user can now configure secondary viewports. Modify the `"listen_port"` on the sensor configuration with any non-zero value to create additional viewports. User can
should we make a note somewhere that this is primarily used for HIL, real time systems, direct injection, etc?

2020-10-09 19:05 UTC, citlaligm commented
@devinaconley updated this tutorial and move to a new section "Common Tutorials" since now there is nothing specific to LV. I think is ready for another look.

2020-10-15 22:59 UTC, katiemacaulay commented on docs/monoDrive_home/Multi viewport.md
> +```
add json after ``` to show as an object.

2020-10-15 23:00 UTC, katiemacaulay commented on docs/monoDrive_home/Multi viewport.md
> +### Multi viewport
This header should only have `#`, and the remaining headers in this file should have `##` to show correctly on the side menu

2020-10-15 23:02 UTC, katiemacaulay commented on docs/monoDrive_home/Multi viewport.md
> +<img class="lg_img" src="../img/multiviewport.png"/>
try `class="wide_img" instead of "lg_img" here. The picture will fill up the entire width, and make it easier to view.

2020-10-15 23:04 UTC, katiemacaulay commented on docs/monoDrive_home/Viewport.md
> +  <img class="wide_img" src="https://github.com/monoDriveIO/documentation/raw/master/WikiPhotos/LV_client/sensors/configuration/viewport/viewport.png" />
Image is not showing.

2020-10-15 23:05 UTC, katiemacaulay reviewed
Just added some formatting notes.

2020-11-04 13:05 UTC, devinaconley commented
@citlaligm just updated the copy here, should be ready for another look!

2020-11-11 21:16 UTC, merged