1.13 Updates/Additions
monoDriveIO/documentation pull request #242
Opened 2020-12-23 15:57 UTC by katiemacaulay

This PR covers some of the changes and updates from 1.12 to 1.13. 

- Instructions for UE version 4.25.6
- Instructions include a link to prerequisites- can be easy to skip
- Some updates to Viewport camera to help guide users who want multiple viewports
- Remove lane spline information but updated the import/export road network widget
- Updated scenario editor/ scenario creation with new pictures and updated info
- Created Vehicle Behavior Trigger Box Page
- Updated Scenario Widget Tool as well. 
- Made some updates to front page text.

Questions/ Suggestions Needed

- Do we want to reorganize the scenario file creation process into a different side panel structure/.md file structure?
- The front page paragraph text needs some updating, please look over/ suggestions welcomed.
- Update camera models that can have a viewport?

2020-12-23 18:22 UTC, plarios commented on docs/FAQ.md
> +     - Cuda is a requirement to run the simulator, see [prerequisites](Getting_Started.md).
the CUDA SDK is a requirement for the scenario editor, not for the simulator

2020-12-23 18:22 UTC, plarios commented on docs/FAQ.md
> +    - monoDrive's Simulator has high quality graphics that will take some time to compile
this also applies only to the scenario editor

2021-01-07 03:35 UTC, citlaligm requested changes
Katie, great job getting all these changes and updates! Just some small changes and adjustments. Looking great!

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/scenarios.md
Need to change the above paragraph:
"The monoDrive Scenario Editor allows users to create their own scenarios by controlling various different aspects of AI vehicle behavior. There are two types of files that can be created: the trajectory file for Replay Mode and the scenario file for Closed loop mode."

Try something like this (feel free to change it):
"The monoDrive Scenario Editor allows users to create their own scenarios by controlling various different aspects of AI vehicle behavior, these scenarios are used when running the simulator or editor on closed loop mode"

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/trigger_boxes.md
> +1. In the vehicle's "Details" window, click the "Add Component" button at the top and search for "Vehicle Behavior Trigger."
I think we should add something like:
"Click the vehicle and then go the "Details" window"

If this the first time user does this, can be a bit strange not to know where is the details window.

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/trigger_boxes.md
> +  - **Other:** "The description of the actions that this box will trigger on the other vehicle.
Remove extra quotes

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/trigger_boxes.md
> +  - **Next Turn Center:** Triggers the vehicle to take the center most lane at the next intersection or lane branch.
Is this correct "center most lane"? may a typo from copy-paste? If so, probably an error on the simulator description, too?

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/scenario_files.md
>  The AI vehicle behavior details and tags that can be altered to create the scenario file can be found in [Scenario Creation](../scenarios)
I feel like this file and the **scenarios** should be merged one section called Scenario File Creation (similar to the Trajectory File Creation)  and there should be a sub-section for the  Scenario Editor and a subsection for the Scenario Setup. What do you think? Or at least have these sections one after another on the left bar.
![image](https://user-images.githubusercontent.com/10260895/103847417-cca1b200-5065-11eb-9edc-21a0bcc26fc1.png)

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/scenario_files.md
>  To begin, find the under the Content Folder.
"find the tool under the Content Folder, right-click and select Run Editor Utility Widget "

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/scenario_files.md
> +Selecting "Save" will write the scene's current configuration file indicated after FilePath. This
indicated on the specified file on FilePath, may be?

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/scenario_files.md
> +will overwrite any paths that have the same name. Clear all will remove all loaded
"will overwrite any file that has the same name."?

2021-01-07 03:35 UTC, citlaligm commented on docs/scenario_editor/scenario_files.md
>    </div>
Can we add a note that, the user needs to Clear All assets on the editor before using any client to playback the scenario? Failing to do that, will cause the vehicles to fly all over the place.

2021-01-07 17:24 UTC, katiemacaulay commented
@citlaligm, ready for another look. thank you for your help!!

2021-01-07 18:31 UTC, citlaligm approved these changes
Looks ready to go!

2021-01-07 18:35 UTC, merged