Removed focal length from fisheye and wide angle lens
monoDriveIO/documentation pull request #288
Opened 2021-05-26 15:20 UTC by katiemacaulay

Removed focal length from fisheye and wide angle lens

2021-05-26 15:23 UTC, stephendb commented
Focal length is removed from all camera sensors and senor size, please check them all.

2021-06-09 14:06 UTC, bradleynull requested changes
@katiemacaulay Looking good! Just a few minor updates to the variable descriptions.

2021-06-09 14:06 UTC, bradleynull commented on docs/monoDrive_home/Camera.md
> +    - **cfa:** The cfa type.
```suggestion
    - **cfa:** The cfa type. Can be any 4 length string consisting of the letters `rgbc`.
```

2021-06-09 14:06 UTC, bradleynull commented on docs/monoDrive_home/Camera.md
> +- **fov:** Controls the horizontal angle of view of the camera. The vertical angle will be dynamically calculated based on `stream_dimensions`.
```suggestion
- **fov:** Controls the horizontal angle of view of the camera. The vertical angle will be dynamically calculated based on `stream_dimensions`. If set to `0` then the camera matrix will be used to compute the field-of-view.
```

2021-06-22 18:34 UTC, bradleynull approved these changes
@katiemacaulay looks good to go. Approved!

2021-06-23 19:04 UTC, merged